# Generated by Django 3.2.5 on 2021-07-30 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_loansrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributions',
            options={'verbose_name_plural': 'Contribution'},
        ),
        migrations.AlterModelOptions(
            name='loansrequest',
            options={'verbose_name_plural': 'Loan Application'},
        ),
    ]
