# Generated by Django 3.2.5 on 2021-08-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210730_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansrequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
